version: "3"
services:
  app:
    build: .
    container_name: soniapp
    volumes:
      - ./app:/var/www/soninet
    ports:
      - 8000:8000
    # command: "python soninet/manage.py runserver 0.0.0.0:8000"